[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "php81Packages.pdo", "php81Packages.mysql"]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
